# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  title = "Saint-Clair Chabert-Liddell"
# Uncomment the lines below to configure your website in a second language.
[fr]
  languageCode = "fr-fr"
  contentDir = "content/fr"
  title = "Saint-Clair Chabert-Liddell"
#  [zh.params]
#    description = "Site description in Chinese..."
  [[fr.menu.main]]
    name = "A propos"
    url = "#about"
    weight = 30
  [[fr.menu.main]]
    name = "Nouvelles"
    url = "#post"
    weight = 35
  [[fr.menu.main]]
    name = "Publications"
    url = "#featured"
    weight = 40
  [[fr.menu.main]]
    name = "Enseignement"
    url = "#teaching"
    weight = 50
  [[fr.menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 60